// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://muvjvnayalcuwcfhgwwq.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11dmp2bmF5YWxjdXdjZmhnd3dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI4MzU4NzUsImV4cCI6MjA0ODQxMTg3NX0.JgddUe_aJlr4SWDMB6x6dYwR_nkIYu6DA4lVRnUACoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);